# Generated by Django 4.1.7 on 2023-04-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='process',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shortDescription',
            field=models.TextField(default='Eat me', max_length=200),
        ),
    ]
