# Generated by Django 4.1.7 on 2023-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_recipe_ingredients_alter_recipe_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='easy',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='eggs',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='family',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='fast',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='fish',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='halal',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='hard',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='highCalorie',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='lactose',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='lowCalorie',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='nuts',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='partners',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='seasonal',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='single',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='soya',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='spicy',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='vegan',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='vegetarian',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='wheat',
            field=models.BooleanField(default=0),
        ),
    ]
