# Generated by Django 4.1.7 on 2023-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_recipe_ingredients_alter_recipe_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='process',
            field=models.TextField(max_length=4000),
        ),
    ]
