# Generated by Django 4.1.7 on 2023-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_recipe_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='No Rating', max_length=24)),
                ('details', models.TextField(max_length=2000)),
                ('anonymous', models.BooleanField(default=False)),
                ('userEmail', models.CharField(default='No Email', max_length=40)),
            ],
        ),
    ]
