# Generated by Django 4.1.7 on 2023-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_rename_useremail_feedback_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='userID',
            field=models.CharField(blank=True, default='No Email', max_length=40),
        ),
    ]
