# Generated by Django 4.1.7 on 2023-04-08 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0008_alter_feedback_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='userID',
            field=models.ForeignKey(blank=True, default='No Email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
