# Generated by Django 4.1.7 on 2023-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_feedback_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('Highly Satisfied', 'highlySatisfied'), ('Satisfied', 'Satisfied'), ('Moderate', 'Moderate'), ('Could Do Better', 'CouldDoBetter'), ('Unsatisfied', 'Unsatisfied')], max_length=24),
        ),
    ]
