# Generated by Django 4.1.7 on 2023-04-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0010_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('highlySatisfied', 'Highly Satisfied'), ('Satisfied', 'Satisfied'), ('Moderate', 'Moderate'), ('CouldDoBetter', 'Could Do Better'), ('Unsatisfied', 'Unsatisfied')], max_length=24),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='userID',
            field=models.ForeignKey(blank=True, default='No ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
