# Generated by Django 4.1.7 on 2023-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_feedback_rating_alter_feedback_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
