# Generated by Django 4.1.7 on 2023-04-09 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0014_alter_favourites_recipeid_alter_favourites_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('spicy', models.BooleanField(default=False)),
                ('lowCalorie', models.BooleanField(default=False)),
                ('highCalorie', models.BooleanField(default=False)),
                ('halal', models.BooleanField(default=False)),
                ('nuts', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('lactose', models.BooleanField(default=False)),
                ('eggs', models.BooleanField(default=False)),
                ('wheat', models.BooleanField(default=False)),
                ('soya', models.BooleanField(default=False)),
                ('seasonal', models.BooleanField(default=False)),
                ('fast', models.BooleanField(default=False)),
                ('easy', models.BooleanField(default=False)),
                ('hard', models.BooleanField(default=False)),
                ('family', models.BooleanField(default=False)),
                ('partners', models.BooleanField(default=False)),
                ('single', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
