# Generated by Django 4.1.7 on 2023-04-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
