# Generated by Django 4.1.7 on 2023-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_remove_tags_eggs_remove_tags_lactose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='eggs',
            field=models.BooleanField(default=False),
        ),
    ]
