# Generated by Django 4.1.7 on 2023-04-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_tags_eggs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='eggs',
        ),
    ]
