# Generated by Django 4.1.7 on 2023-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0022_remove_tags_eggs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='lactose',
            field=models.BooleanField(default=False),
        ),
    ]
