# Generated by Django 4.1.7 on 2023-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0023_tags_lactose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
