# Generated by Django 4.1.7 on 2023-04-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0024_alter_ratings_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularuser',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='regularuser',
            name='clearance',
        ),
    ]
