services:
  goodrecipe:
    image: goodrecipe
    build:
      context: .
      dockerfile: DockerFile
    restart: unless-stopped
    ports:
      - "8000:8000"
    entrypoint: ["./goodrecipe-entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:latest
    container_name: goodrecipe-mysql_db
    environment:
      MYSQL_DATABASE: goodrecipe-mysql_db
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_USER: user1
      MYSQL_PASSWORD: user123#
    ports:
    - '3309:3306'
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/mysql/db:/var/lib/mysql
      